const initialSetup = {
  0: { name: "rook", color: "black" },
  1: { name: "knight", color: "black" },
  2: { name: "bishop", color: "black" },
  3: { name: "queen", color: "black" },
  4: { name: "king", color: "black" },
  5: { name: "bishop", color: "black" },
  6: { name: "knight", color: "black" },
  7: { name: "rook", color: "black" },
  8: { name: "pawn", color: "black" },
  9: { name: "pawn", color: "black" },
  10: { name: "pawn", color: "black" },
  11: { name: "pawn", color: "black" },
  12: { name: "pawn", color: "black" },
  13: { name: "pawn", color: "black" },
  14: { name: "pawn", color: "black" },
  15: { name: "pawn", color: "black" },
  48: { name: "pawn", color: "white" },
  49: { name: "pawn", color: "white" },
  50: { name: "pawn", color: "white" },
  51: { name: "pawn", color: "white" },
  52: { name: "pawn", color: "white" },
  53: { name: "pawn", color: "white" },
  54: { name: "pawn", color: "white" },
  55: { name: "pawn", color: "white" },
  56: { name: "rook", color: "white" },
  57: { name: "knight", color: "white" },
  58: { name: "bishop", color: "white" },
  59: { name: "queen", color: "white" },
  60: { name: "king", color: "white" },
  61: { name: "bishop", color: "white" },
  62: { name: "knight", color: "white" },
  63: { name: "rook", color: "white" },
}

export default initialSetup