const initialSetup = [
  { x: 0, y: 0, name: "rook", color: "black" },
  { x: 1, y: 0, name: "knight", color: "black" },
  { x: 2, y: 0, name: "bishop", color: "black" },
  { x: 3, y: 0, name: "queen", color: "black" },
  { x: 4, y: 0, name: "king", color: "black" },
  { x: 5, y: 0, name: "bishop", color: "black" },
  { x: 6, y: 0, name: "knight", color: "black" },
  { x: 7, y: 0, name: "rook", color: "black" },
  { x: 0, y: 1, name: "pawn", color: "black" },
  { x: 1, y: 1, name: "pawn", color: "black" },
  { x: 2, y: 1, name: "pawn", color: "black" },
  { x: 3, y: 1, name: "pawn", color: "black" },
  { x: 4, y: 1, name: "pawn", color: "black" },
  { x: 5, y: 1, name: "pawn", color: "black" },
  { x: 6, y: 1, name: "pawn", color: "black" },
  { x: 7, y: 1, name: "pawn", color: "black" },
  { x: 0, y: 6, name: "pawn", color: "white" },
  { x: 1, y: 6, name: "pawn", color: "white" },
  { x: 2, y: 6, name: "pawn", color: "white" },
  { x: 3, y: 6, name: "pawn", color: "white" },
  { x: 4, y: 6, name: "pawn", color: "white" },
  { x: 5, y: 6, name: "pawn", color: "white" },
  { x: 6, y: 6, name: "pawn", color: "white" },
  { x: 7, y: 6, name: "pawn", color: "white" },
  { x: 0, y: 7, name: "rook", color: "white" },
  { x: 1, y: 7, name: "knight", color: "white" },
  { x: 2, y: 7, name: "bishop", color: "white" },
  { x: 3, y: 7, name: "queen", color: "white" },
  { x: 4, y: 7, name: "king", color: "white" },
  { x: 5, y: 7, name: "bishop", color: "white" },
  { x: 6, y: 7, name: "knight", color: "white" },
  { x: 7, y: 7, name: "rook", color: "white" },
]

export default initialSetup